services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "127.0.0.1:3306:3306"
    restart: always

  sonarqube:
    ports:
      - "9000:9000"
    restart: always

  backend:
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    restart: always

  frontend:
    restart: always

  nginx:
    ports:
      - "80:80"
    restart: always
    profiles: []
