sonar.projectKey=CMS-frontend
sonar.projectName=CMS Frontend (Nuxt)
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=node_modules/**,dist/**,.output/**,.nuxt/**
sonar.sourceEncoding=UTF-8
sonar.language=ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
