
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  ArticleCard: typeof import("../../app/components/ArticleCard.vue")['default']
  Dialog: typeof import("../../app/components/Dialog.vue")['default']
  Header: typeof import("../../app/components/Header.vue")['default']
  Menu: typeof import("../../app/components/Menu.vue")['default']
  RichTextEditor: typeof import("../../app/components/RichTextEditor.vue")['default']
  NuxtWelcome: typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
  NuxtLayout: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  NuxtErrorBoundary: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  ClientOnly: typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
  DevOnly: typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
  ServerPlaceholder: typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
  NuxtLink: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  NuxtLoadingIndicator: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  NuxtTime: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  NuxtRouteAnnouncer: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  NuxtAnnouncer: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']
  NuxtImg: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
  NuxtPicture: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
  ElAnchor: typeof import("../../node_modules/element-plus/es/components/anchor/index")['ElAnchor']
  ElAffix: typeof import("../../node_modules/element-plus/es/components/affix/index")['ElAffix']
  ElAlert: typeof import("../../node_modules/element-plus/es/components/alert/index")['ElAlert']
  ElAnchorLink: typeof import("../../node_modules/element-plus/es/components/anchor/index")['ElAnchorLink']
  ElAutocomplete: typeof import("../../node_modules/element-plus/es/components/autocomplete/index")['ElAutocomplete']
  ElAside: typeof import("../../node_modules/element-plus/es/components/container/index")['ElAside']
  ElAvatar: typeof import("../../node_modules/element-plus/es/components/avatar/index")['ElAvatar']
  ElAutoResizer: typeof import("../../node_modules/element-plus/es/components/table-v2/index")['ElAutoResizer']
  ElAvatarGroup: typeof import("../../node_modules/element-plus/es/components/avatar/index")['ElAvatarGroup']
  ElButtonGroup: typeof import("../../node_modules/element-plus/es/components/button/index")['ElButtonGroup']
  ElBadge: typeof import("../../node_modules/element-plus/es/components/badge/index")['ElBadge']
  ElBreadcrumbItem: typeof import("../../node_modules/element-plus/es/components/breadcrumb/index")['ElBreadcrumbItem']
  ElCalendar: typeof import("../../node_modules/element-plus/es/components/calendar/index")['ElCalendar']
  ElCascader: typeof import("../../node_modules/element-plus/es/components/cascader/index")['ElCascader']
  ElCarousel: typeof import("../../node_modules/element-plus/es/components/carousel/index")['ElCarousel']
  ElCard: typeof import("../../node_modules/element-plus/es/components/card/index")['ElCard']
  ElCheckboxButton: typeof import("../../node_modules/element-plus/es/components/checkbox/index")['ElCheckboxButton']
  ElCarouselItem: typeof import("../../node_modules/element-plus/es/components/carousel/index")['ElCarouselItem']
  ElCheckbox: typeof import("../../node_modules/element-plus/es/components/checkbox/index")['ElCheckbox']
  ElCascaderPanel: typeof import("../../node_modules/element-plus/es/components/cascader-panel/index")['ElCascaderPanel']
  ElCol: typeof import("../../node_modules/element-plus/es/components/col/index")['ElCol']
  ElBacktop: typeof import("../../node_modules/element-plus/es/components/backtop/index")['ElBacktop']
  ElCheckTag: typeof import("../../node_modules/element-plus/es/components/check-tag/index")['ElCheckTag']
  ElCollapseItem: typeof import("../../node_modules/element-plus/es/components/collapse/index")['ElCollapseItem']
  ElCheckboxGroup: typeof import("../../node_modules/element-plus/es/components/checkbox/index")['ElCheckboxGroup']
  ElBreadcrumb: typeof import("../../node_modules/element-plus/es/components/breadcrumb/index")['ElBreadcrumb']
  ElCollapseTransition: typeof import("../../node_modules/element-plus/es/components/collapse-transition/index")['ElCollapseTransition']
  ElButton: typeof import("../../node_modules/element-plus/es/components/button/index")['ElButton']
  ElCollapse: typeof import("../../node_modules/element-plus/es/components/collapse/index")['ElCollapse']
  ElColorPickerPanel: typeof import("../../node_modules/element-plus/es/components/color-picker-panel/index")['ElColorPickerPanel']
  ElColorPicker: typeof import("../../node_modules/element-plus/es/components/color-picker/index")['ElColorPicker']
  ElConfigProvider: typeof import("../../node_modules/element-plus/es/components/config-provider/index")['ElConfigProvider']
  ElCountdown: typeof import("../../node_modules/element-plus/es/components/countdown/index")['ElCountdown']
  ElContainer: typeof import("../../node_modules/element-plus/es/components/container/index")['ElContainer']
  ElDialog: typeof import("../../node_modules/element-plus/es/components/dialog/index")['ElDialog']
  ElDatePicker: typeof import("../../node_modules/element-plus/es/components/date-picker/index")['ElDatePicker']
  ElDatePickerPanel: typeof import("../../node_modules/element-plus/es/components/date-picker-panel/index")['ElDatePickerPanel']
  ElDescriptions: typeof import("../../node_modules/element-plus/es/components/descriptions/index")['ElDescriptions']
  ElDescriptionsItem: typeof import("../../node_modules/element-plus/es/components/descriptions/index")['ElDescriptionsItem']
  ElDrawer: typeof import("../../node_modules/element-plus/es/components/drawer/index")['ElDrawer']
  ElDropdownItem: typeof import("../../node_modules/element-plus/es/components/dropdown/index")['ElDropdownItem']
  ElDivider: typeof import("../../node_modules/element-plus/es/components/divider/index")['ElDivider']
  ElFooter: typeof import("../../node_modules/element-plus/es/components/container/index")['ElFooter']
  ElDropdown: typeof import("../../node_modules/element-plus/es/components/dropdown/index")['ElDropdown']
  ElForm: typeof import("../../node_modules/element-plus/es/components/form/index")['ElForm']
  ElEmpty: typeof import("../../node_modules/element-plus/es/components/empty/index")['ElEmpty']
  ElDropdownMenu: typeof import("../../node_modules/element-plus/es/components/dropdown/index")['ElDropdownMenu']
  ElImage: typeof import("../../node_modules/element-plus/es/components/image/index")['ElImage']
  ElFormItem: typeof import("../../node_modules/element-plus/es/components/form/index")['ElFormItem']
  ElHeader: typeof import("../../node_modules/element-plus/es/components/container/index")['ElHeader']
  ElInput: typeof import("../../node_modules/element-plus/es/components/input/index")['ElInput']
  ElIcon: typeof import("../../node_modules/element-plus/es/components/icon/index")['ElIcon']
  ElImageViewer: typeof import("../../node_modules/element-plus/es/components/image-viewer/index")['ElImageViewer']
  ElInputNumber: typeof import("../../node_modules/element-plus/es/components/input-number/index")['ElInputNumber']
  ElLink: typeof import("../../node_modules/element-plus/es/components/link/index")['ElLink']
  ElMain: typeof import("../../node_modules/element-plus/es/components/container/index")['ElMain']
  ElInputTag: typeof import("../../node_modules/element-plus/es/components/input-tag/index")['ElInputTag']
  ElInputOtp: typeof import("../../node_modules/element-plus/es/components/input-otp/index")['ElInputOtp']
  ElMenu: typeof import("../../node_modules/element-plus/es/components/menu/index")['ElMenu']
  ElMention: typeof import("../../node_modules/element-plus/es/components/mention/index")['ElMention']
  ElMenuItem: typeof import("../../node_modules/element-plus/es/components/menu/index")['ElMenuItem']
  ElMenuItemGroup: typeof import("../../node_modules/element-plus/es/components/menu/index")['ElMenuItemGroup']
  ElOptionGroup: typeof import("../../node_modules/element-plus/es/components/select/index")['ElOptionGroup']
  ElOption: typeof import("../../node_modules/element-plus/es/components/select/index")['ElOption']
  ElOverlay: typeof import("../../node_modules/element-plus/es/components/overlay/index")['ElOverlay']
  ElPageHeader: typeof import("../../node_modules/element-plus/es/components/page-header/index")['ElPageHeader']
  ElPagination: typeof import("../../node_modules/element-plus/es/components/pagination/index")['ElPagination']
  ElPopconfirm: typeof import("../../node_modules/element-plus/es/components/popconfirm/index")['ElPopconfirm']
  ElPopper: typeof import("../../node_modules/element-plus/es/components/popper/index")['ElPopper']
  ElPopover: typeof import("../../node_modules/element-plus/es/components/popover/index")['ElPopover']
  ElPopperContent: typeof import("../../node_modules/element-plus/es/components/popper/index")['ElPopperContent']
  ElPopperArrow: typeof import("../../node_modules/element-plus/es/components/popper/index")['ElPopperArrow']
  ElProgress: typeof import("../../node_modules/element-plus/es/components/progress/index")['ElProgress']
  ElRadio: typeof import("../../node_modules/element-plus/es/components/radio/index")['ElRadio']
  ElPopperTrigger: typeof import("../../node_modules/element-plus/es/components/popper/index")['ElPopperTrigger']
  ElRadioButton: typeof import("../../node_modules/element-plus/es/components/radio/index")['ElRadioButton']
  ElRadioGroup: typeof import("../../node_modules/element-plus/es/components/radio/index")['ElRadioGroup']
  ElRow: typeof import("../../node_modules/element-plus/es/components/row/index")['ElRow']
  ElRate: typeof import("../../node_modules/element-plus/es/components/rate/index")['ElRate']
  ElResult: typeof import("../../node_modules/element-plus/es/components/result/index")['ElResult']
  ElScrollbar: typeof import("../../node_modules/element-plus/es/components/scrollbar/index")['ElScrollbar']
  ElSelect: typeof import("../../node_modules/element-plus/es/components/select/index")['ElSelect']
  ElSelectV2: typeof import("../../node_modules/element-plus/es/components/select-v2/index")['ElSelectV2']
  ElSkeletonItem: typeof import("../../node_modules/element-plus/es/components/skeleton/index")['ElSkeletonItem']
  ElSplitterPanel: typeof import("../../node_modules/element-plus/es/components/splitter/index")['ElSplitterPanel']
  ElSegmented: typeof import("../../node_modules/element-plus/es/components/segmented/index")['ElSegmented']
  ElSkeleton: typeof import("../../node_modules/element-plus/es/components/skeleton/index")['ElSkeleton']
  ElSlider: typeof import("../../node_modules/element-plus/es/components/slider/index")['ElSlider']
  ElSplitter: typeof import("../../node_modules/element-plus/es/components/splitter/index")['ElSplitter']
  ElSpace: typeof import("../../node_modules/element-plus/es/components/space/index")['ElSpace']
  ElStatistic: typeof import("../../node_modules/element-plus/es/components/statistic/index")['ElStatistic']
  ElStep: typeof import("../../node_modules/element-plus/es/components/steps/index")['ElStep']
  ElTabPane: typeof import("../../node_modules/element-plus/es/components/tabs/index")['ElTabPane']
  ElSteps: typeof import("../../node_modules/element-plus/es/components/steps/index")['ElSteps']
  ElSubMenu: typeof import("../../node_modules/element-plus/es/components/menu/index")['ElSubMenu']
  ElTable: typeof import("../../node_modules/element-plus/es/components/table/index")['ElTable']
  ElSwitch: typeof import("../../node_modules/element-plus/es/components/switch/index")['ElSwitch']
  ElTabs: typeof import("../../node_modules/element-plus/es/components/tabs/index")['ElTabs']
  ElTableColumn: typeof import("../../node_modules/element-plus/es/components/table/index")['ElTableColumn']
  ElTableV2: typeof import("../../node_modules/element-plus/es/components/table-v2/index")['ElTableV2']
  ElTag: typeof import("../../node_modules/element-plus/es/components/tag/index")['ElTag']
  ElText: typeof import("../../node_modules/element-plus/es/components/text/index")['ElText']
  ElTimePicker: typeof import("../../node_modules/element-plus/es/components/time-picker/index")['ElTimePicker']
  ElTimeSelect: typeof import("../../node_modules/element-plus/es/components/time-select/index")['ElTimeSelect']
  ElTimeline: typeof import("../../node_modules/element-plus/es/components/timeline/index")['ElTimeline']
  ElTour: typeof import("../../node_modules/element-plus/es/components/tour/index")['ElTour']
  ElTimelineItem: typeof import("../../node_modules/element-plus/es/components/timeline/index")['ElTimelineItem']
  ElTooltip: typeof import("../../node_modules/element-plus/es/components/tooltip/index")['ElTooltip']
  ElIconAddLocation: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['AddLocation']
  ElTourStep: typeof import("../../node_modules/element-plus/es/components/tour/index")['ElTourStep']
  ElTransfer: typeof import("../../node_modules/element-plus/es/components/transfer/index")['ElTransfer']
  ElIconAim: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Aim']
  ElIconAlarmClock: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['AlarmClock']
  ElIconApple: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Apple']
  ElIconArrowLeftBold: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowLeftBold']
  ElTree: typeof import("../../node_modules/element-plus/es/components/tree/index")['ElTree']
  ElTreeSelect: typeof import("../../node_modules/element-plus/es/components/tree-select/index")['ElTreeSelect']
  ElIconArrowDownBold: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowDownBold']
  ElUpload: typeof import("../../node_modules/element-plus/es/components/upload/index")['ElUpload']
  ElTreeV2: typeof import("../../node_modules/element-plus/es/components/tree-v2/index")['ElTreeV2']
  ElIconArrowLeft: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowLeft']
  ElWatermark: typeof import("../../node_modules/element-plus/es/components/watermark/index")['ElWatermark']
  ElIconArrowRightBold: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowRightBold']
  ElIconArrowDown: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowDown']
  ElIconAvatar: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Avatar']
  ElIconArrowUpBold: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowUpBold']
  ElIconArrowUp: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowUp']
  ElIconArrowRight: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowRight']
  ElIconBell: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Bell']
  ElIconBack: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Back']
  ElIconBellFilled: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['BellFilled']
  ElIconBasketball: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Basketball']
  ElIconBaseball: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Baseball']
  ElIconBottomLeft: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['BottomLeft']
  ElIconBottom: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Bottom']
  ElIconBox: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Box']
  ElIconBicycle: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Bicycle']
  ElIconBottomRight: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['BottomRight']
  ElIconBrushFilled: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['BrushFilled']
  ElIconBrush: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Brush']
  ElIconCamera: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Camera']
  ElIconBriefcase: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Briefcase']
  ElIconBurger: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Burger']
  ElIconBowl: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Bowl']
  ElIconCameraFilled: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CameraFilled']
  ElIconCalendar: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Calendar']
  ElIconCaretBottom: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CaretBottom']
  ElIconCaretLeft: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CaretLeft']
  ElIconChatLineSquare: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ChatLineSquare']
  ElIconCaretRight: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CaretRight']
  ElIconCellphone: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Cellphone']
  ElIconChatDotSquare: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ChatDotSquare']
  ElIconChatLineRound: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ChatLineRound']
  ElIconCaretTop: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CaretTop']
  ElIconChatRound: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ChatRound']
  ElIconChatDotRound: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ChatDotRound']
  ElIconChecked: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Checked']
  ElIconCherry: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Cherry']
  ElIconCheck: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Check']
  ElIconChatSquare: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ChatSquare']
  ElIconChromeFilled: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ChromeFilled']
  ElIconCircleCloseFilled: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CircleCloseFilled']
  ElIconChicken: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Chicken']
  ElIconCirclePlus: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CirclePlus']
  ElIconCircleClose: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CircleClose']
  ElIconCircleCheckFilled: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CircleCheckFilled']
  ElIconClock: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Clock']
  ElIconClose: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Close']
  ElIconCircleCheck: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CircleCheck']
  ElIconCoin: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Coin']
  ElIconCirclePlusFilled: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CirclePlusFilled']
  ElIconCloudy: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Cloudy']
  ElIconCloseBold: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CloseBold']
  ElIconCoffee: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Coffee']
  ElIconColdDrink: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ColdDrink']
  ElIconCoffeeCup: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CoffeeCup']
  ElIconCoordinate: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Coordinate']
  ElIconCollection: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Collection']
  ElIconCompass: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Compass']
  ElIconCollectionTag: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CollectionTag']
  ElIconConnection: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Connection']
  ElIconComment: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Comment']
  ElIconCreditCard: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CreditCard']
  ElIconCrop: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Crop']
  ElIconCpu: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Cpu']
  ElIconDArrowLeft: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DArrowLeft']
  ElIconCopyDocument: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CopyDocument']
  ElIconDataLine: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DataLine']
  ElIconDArrowRight: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DArrowRight']
  ElIconDCaret: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DCaret']
  ElIconDelete: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Delete']
  ElIconDeleteFilled: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DeleteFilled']
  ElIconDataAnalysis: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DataAnalysis']
  ElIconDataBoard: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DataBoard']
  ElIconDessert: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Dessert']
  ElIconDishDot: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DishDot']
  ElIconDiscount: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Discount']
  ElIconDeleteLocation: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DeleteLocation']
  ElIconDish: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Dish']
  ElIconDocumentCopy: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DocumentCopy']
  ElIconDocumentAdd: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DocumentAdd']
  ElIconDocument: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Document']
  ElIconDocumentDelete: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DocumentDelete']
  ElIconDocumentChecked: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DocumentChecked']
  ElIconEdit: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Edit']
  ElIconDocumentRemove: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DocumentRemove']
  ElIconEditPen: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['EditPen']
  ElIconEleme: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Eleme']
  ElIconElemeFilled: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ElemeFilled']
  ElIconDownload: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Download']
  ElIconFailed: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Failed']
  ElIconExpand: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Expand']
  ElIconElementPlus: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ElementPlus']
  ElIconFemale: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Female']
  ElIconFilm: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Film']
  ElIconDrizzling: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Drizzling']
  ElIconFinished: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Finished']
  ElIconFirstAidKit: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['FirstAidKit']
  ElIconFlag: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Flag']
  ElIconFilter: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Filter']
  ElIconFiles: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Files']
  ElIconFold: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Fold']
  ElIconFolderChecked: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['FolderChecked']
  ElIconFolder: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Folder']
  ElIconFolderAdd: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['FolderAdd']
  ElIconFolderRemove: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['FolderRemove']
  ElIconFood: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Food']
  ElIconFolderDelete: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['FolderDelete']
  ElIconFolderOpened: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['FolderOpened']
  ElIconFries: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Fries']
  ElIconGoblet: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Goblet']
  ElIconForkSpoon: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ForkSpoon']
  ElIconGobletFull: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['GobletFull']
  ElIconFootball: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Football']
  ElIconGobletSquare: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['GobletSquare']
  ElIconGoldMedal: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['GoldMedal']
  ElIconFullScreen: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['FullScreen']
  ElIconGobletSquareFull: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['GobletSquareFull']
  ElIconGoodsFilled: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['GoodsFilled']
  ElIconGoods: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Goods']
  ElIconGrid: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Grid']
  ElIconHeadset: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Headset']
  ElIconHandbag: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Handbag']
  ElIconGuide: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Guide']
  ElIconHelp: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Help']
  ElIconHelpFilled: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['HelpFilled']
  ElIconHide: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Hide']
  ElIconHomeFilled: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['HomeFilled']
  ElIconHistogram: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Histogram']
  ElIconGrape: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Grape']
  ElIconHouse: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['House']
  ElIconIceCreamSquare: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['IceCreamSquare']
  ElIconIceDrink: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['IceDrink']
  ElIconIceCreamRound: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['IceCreamRound']
  ElIconHotWater: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['HotWater']
  ElIconIceCream: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['IceCream']
  ElIconInfoFilled: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['InfoFilled']
  ElIconIphone: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Iphone']
  ElIconKey: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Key']
  ElIconLightning: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Lightning']
  ElIconKnifeFork: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['KnifeFork']
  ElIconIceTea: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['IceTea']
  ElIconLocation: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Location']
  ElIconLink: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Link']
  ElIconList: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['List']
  ElIconLocationFilled: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['LocationFilled']
  ElIconLoading: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Loading']
  ElIconLocationInformation: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['LocationInformation']
  ElIconLock: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Lock']
  ElIconMagnet: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Magnet']
  ElIconMagicStick: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MagicStick']
  ElIconLollipop: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Lollipop']
  ElIconMenu: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Menu']
  ElIconMedal: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Medal']
  ElIconManagement: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Management']
  ElIconMapLocation: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MapLocation']
  ElIconMale: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Male']
  ElIconMemo: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Memo']
  ElIconMessage: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Message']
  ElIconMicrophone: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Microphone']
  ElIconMoney: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Money']
  ElIconMic: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Mic']
  ElIconMinus: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Minus']
  ElIconMoon: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Moon']
  ElIconMilkTea: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MilkTea']
  ElIconMoonNight: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MoonNight']
  ElIconMonitor: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Monitor']
  ElIconMessageBox: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MessageBox']
  ElIconMostlyCloudy: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MostlyCloudy']
  ElIconMore: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['More']
  ElIconMoreFilled: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MoreFilled']
  ElIconNoSmoking: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['NoSmoking']
  ElIconMuteNotification: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MuteNotification']
  ElIconMouse: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Mouse']
  ElIconMute: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Mute']
  ElIconMug: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Mug']
  ElIconNotebook: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Notebook']
  ElIconNotification: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Notification']
  ElIconOfficeBuilding: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['OfficeBuilding']
  ElIconOdometer: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Odometer']
  ElIconOpen: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Open']
  ElIconOperation: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Operation']
  ElIconOrange: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Orange']
  ElIconPaperclip: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Paperclip']
  ElIconPicture: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Picture']
  ElIconPartlyCloudy: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['PartlyCloudy']
  ElIconOpportunity: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Opportunity']
  ElIconPhone: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Phone']
  ElIconPear: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Pear']
  ElIconPictureRounded: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['PictureRounded']
  ElIconPictureFilled: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['PictureFilled']
  ElIconPieChart: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['PieChart']
  ElIconPlatform: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Platform']
  ElIconPhoneFilled: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['PhoneFilled']
  ElIconPlus: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Plus']
  ElIconPosition: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Position']
  ElIconPointer: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Pointer']
  ElIconPostcard: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Postcard']
  ElIconPlace: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Place']
  ElIconPresent: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Present']
  ElIconPouring: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Pouring']
  ElIconPriceTag: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['PriceTag']
  ElIconRank: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Rank']
  ElIconReading: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Reading']
  ElIconQuartzWatch: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['QuartzWatch']
  ElIconPrinter: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Printer']
  ElIconPromotion: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Promotion']
  ElIconReadingLamp: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ReadingLamp']
  ElIconRefreshLeft: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['RefreshLeft']
  ElIconQuestionFilled: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['QuestionFilled']
  ElIconRemove: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Remove']
  ElIconRemoveFilled: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['RemoveFilled']
  ElIconRefrigerator: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Refrigerator']
  ElIconRefreshRight: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['RefreshRight']
  ElIconScaleToOriginal: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ScaleToOriginal']
  ElIconSchool: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['School']
  ElIconRefresh: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Refresh']
  ElIconRight: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Right']
  ElIconScissor: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Scissor']
  ElIconSetting: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Setting']
  ElIconSearch: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Search']
  ElIconSelect: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Select']
  ElIconSemiSelect: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SemiSelect']
  ElIconSetUp: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SetUp']
  ElIconSell: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Sell']
  ElIconShare: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Share']
  ElIconService: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Service']
  ElIconShip: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Ship']
  ElIconShoppingBag: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ShoppingBag']
  ElIconShoppingTrolley: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ShoppingTrolley']
  ElIconShoppingCartFull: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ShoppingCartFull']
  ElIconShop: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Shop']
  ElIconSmoking: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Smoking']
  ElIconSoldOut: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SoldOut']
  ElIconSort: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Sort']
  ElIconShoppingCart: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ShoppingCart']
  ElIconSoccer: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Soccer']
  ElIconSortDown: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SortDown']
  ElIconStamp: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Stamp']
  ElIconSortUp: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SortUp']
  ElIconSuccessFilled: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SuccessFilled']
  ElIconStar: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Star']
  ElIconStopwatch: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Stopwatch']
  ElIconStarFilled: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['StarFilled']
  ElIconSuitcaseLine: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SuitcaseLine']
  ElIconSugar: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Sugar']
  ElIconSuitcase: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Suitcase']
  ElIconSwitch: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Switch']
  ElIconSunny: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Sunny']
  ElIconSunrise: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Sunrise']
  ElIconSunset: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Sunset']
  ElIconSwitchButton: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SwitchButton']
  ElIconTakeawayBox: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['TakeawayBox']
  ElIconTicket: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Ticket']
  ElIconSwitchFilled: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SwitchFilled']
  ElIconTools: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Tools']
  ElIconTopRight: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['TopRight']
  ElIconTimer: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Timer']
  ElIconTickets: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Tickets']
  ElIconTop: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Top']
  ElIconToiletPaper: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ToiletPaper']
  ElIconTrendCharts: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['TrendCharts']
  ElIconTrophyBase: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['TrophyBase']
  ElIconTrophy: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Trophy']
  ElIconTopLeft: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['TopLeft']
  ElIconUmbrella: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Umbrella']
  ElIconUpload: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Upload']
  ElIconUnlock: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Unlock']
  ElIconUploadFilled: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['UploadFilled']
  ElIconUserFilled: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['UserFilled']
  ElIconUser: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['User']
  ElIconTurnOff: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['TurnOff']
  ElIconVan: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Van']
  ElIconVideoCameraFilled: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['VideoCameraFilled']
  ElIconVideoPause: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['VideoPause']
  ElIconVideoCamera: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['VideoCamera']
  ElIconVideoPlay: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['VideoPlay']
  ElIconWalletFilled: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['WalletFilled']
  ElIconView: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['View']
  ElIconWallet: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Wallet']
  ElIconWatermelon: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Watermelon']
  ElIconWarning: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Warning']
  ElIconWarnTriangleFilled: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['WarnTriangleFilled']
  ElIconWatch: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Watch']
  ElIconZoomIn: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ZoomIn']
  ElIconZoomOut: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ZoomOut']
  ElIconWindPower: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['WindPower']
  ElIconWarningFilled: typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['WarningFilled']
  NuxtPage: typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
  NoScript: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
  Link: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
  Base: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
  Title: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
  Meta: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
  Style: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
  Head: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
  Html: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
  Body: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
  NuxtIsland: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
  LazyArticleCard: LazyComponent<typeof import("../../app/components/ArticleCard.vue")['default']>
  LazyDialog: LazyComponent<typeof import("../../app/components/Dialog.vue")['default']>
  LazyHeader: LazyComponent<typeof import("../../app/components/Header.vue")['default']>
  LazyMenu: LazyComponent<typeof import("../../app/components/Menu.vue")['default']>
  LazyRichTextEditor: LazyComponent<typeof import("../../app/components/RichTextEditor.vue")['default']>
  LazyNuxtWelcome: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  LazyNuxtLayout: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  LazyNuxtErrorBoundary: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  LazyClientOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
  LazyDevOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
  LazyServerPlaceholder: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  LazyNuxtLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  LazyNuxtTime: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  LazyNuxtAnnouncer: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']>
  LazyNuxtImg: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
  LazyNuxtPicture: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
  LazyElAnchor: LazyComponent<typeof import("../../node_modules/element-plus/es/components/anchor/index")['ElAnchor']>
  LazyElAffix: LazyComponent<typeof import("../../node_modules/element-plus/es/components/affix/index")['ElAffix']>
  LazyElAlert: LazyComponent<typeof import("../../node_modules/element-plus/es/components/alert/index")['ElAlert']>
  LazyElAnchorLink: LazyComponent<typeof import("../../node_modules/element-plus/es/components/anchor/index")['ElAnchorLink']>
  LazyElAutocomplete: LazyComponent<typeof import("../../node_modules/element-plus/es/components/autocomplete/index")['ElAutocomplete']>
  LazyElAside: LazyComponent<typeof import("../../node_modules/element-plus/es/components/container/index")['ElAside']>
  LazyElAvatar: LazyComponent<typeof import("../../node_modules/element-plus/es/components/avatar/index")['ElAvatar']>
  LazyElAutoResizer: LazyComponent<typeof import("../../node_modules/element-plus/es/components/table-v2/index")['ElAutoResizer']>
  LazyElAvatarGroup: LazyComponent<typeof import("../../node_modules/element-plus/es/components/avatar/index")['ElAvatarGroup']>
  LazyElButtonGroup: LazyComponent<typeof import("../../node_modules/element-plus/es/components/button/index")['ElButtonGroup']>
  LazyElBadge: LazyComponent<typeof import("../../node_modules/element-plus/es/components/badge/index")['ElBadge']>
  LazyElBreadcrumbItem: LazyComponent<typeof import("../../node_modules/element-plus/es/components/breadcrumb/index")['ElBreadcrumbItem']>
  LazyElCalendar: LazyComponent<typeof import("../../node_modules/element-plus/es/components/calendar/index")['ElCalendar']>
  LazyElCascader: LazyComponent<typeof import("../../node_modules/element-plus/es/components/cascader/index")['ElCascader']>
  LazyElCarousel: LazyComponent<typeof import("../../node_modules/element-plus/es/components/carousel/index")['ElCarousel']>
  LazyElCard: LazyComponent<typeof import("../../node_modules/element-plus/es/components/card/index")['ElCard']>
  LazyElCheckboxButton: LazyComponent<typeof import("../../node_modules/element-plus/es/components/checkbox/index")['ElCheckboxButton']>
  LazyElCarouselItem: LazyComponent<typeof import("../../node_modules/element-plus/es/components/carousel/index")['ElCarouselItem']>
  LazyElCheckbox: LazyComponent<typeof import("../../node_modules/element-plus/es/components/checkbox/index")['ElCheckbox']>
  LazyElCascaderPanel: LazyComponent<typeof import("../../node_modules/element-plus/es/components/cascader-panel/index")['ElCascaderPanel']>
  LazyElCol: LazyComponent<typeof import("../../node_modules/element-plus/es/components/col/index")['ElCol']>
  LazyElBacktop: LazyComponent<typeof import("../../node_modules/element-plus/es/components/backtop/index")['ElBacktop']>
  LazyElCheckTag: LazyComponent<typeof import("../../node_modules/element-plus/es/components/check-tag/index")['ElCheckTag']>
  LazyElCollapseItem: LazyComponent<typeof import("../../node_modules/element-plus/es/components/collapse/index")['ElCollapseItem']>
  LazyElCheckboxGroup: LazyComponent<typeof import("../../node_modules/element-plus/es/components/checkbox/index")['ElCheckboxGroup']>
  LazyElBreadcrumb: LazyComponent<typeof import("../../node_modules/element-plus/es/components/breadcrumb/index")['ElBreadcrumb']>
  LazyElCollapseTransition: LazyComponent<typeof import("../../node_modules/element-plus/es/components/collapse-transition/index")['ElCollapseTransition']>
  LazyElButton: LazyComponent<typeof import("../../node_modules/element-plus/es/components/button/index")['ElButton']>
  LazyElCollapse: LazyComponent<typeof import("../../node_modules/element-plus/es/components/collapse/index")['ElCollapse']>
  LazyElColorPickerPanel: LazyComponent<typeof import("../../node_modules/element-plus/es/components/color-picker-panel/index")['ElColorPickerPanel']>
  LazyElColorPicker: LazyComponent<typeof import("../../node_modules/element-plus/es/components/color-picker/index")['ElColorPicker']>
  LazyElConfigProvider: LazyComponent<typeof import("../../node_modules/element-plus/es/components/config-provider/index")['ElConfigProvider']>
  LazyElCountdown: LazyComponent<typeof import("../../node_modules/element-plus/es/components/countdown/index")['ElCountdown']>
  LazyElContainer: LazyComponent<typeof import("../../node_modules/element-plus/es/components/container/index")['ElContainer']>
  LazyElDialog: LazyComponent<typeof import("../../node_modules/element-plus/es/components/dialog/index")['ElDialog']>
  LazyElDatePicker: LazyComponent<typeof import("../../node_modules/element-plus/es/components/date-picker/index")['ElDatePicker']>
  LazyElDatePickerPanel: LazyComponent<typeof import("../../node_modules/element-plus/es/components/date-picker-panel/index")['ElDatePickerPanel']>
  LazyElDescriptions: LazyComponent<typeof import("../../node_modules/element-plus/es/components/descriptions/index")['ElDescriptions']>
  LazyElDescriptionsItem: LazyComponent<typeof import("../../node_modules/element-plus/es/components/descriptions/index")['ElDescriptionsItem']>
  LazyElDrawer: LazyComponent<typeof import("../../node_modules/element-plus/es/components/drawer/index")['ElDrawer']>
  LazyElDropdownItem: LazyComponent<typeof import("../../node_modules/element-plus/es/components/dropdown/index")['ElDropdownItem']>
  LazyElDivider: LazyComponent<typeof import("../../node_modules/element-plus/es/components/divider/index")['ElDivider']>
  LazyElFooter: LazyComponent<typeof import("../../node_modules/element-plus/es/components/container/index")['ElFooter']>
  LazyElDropdown: LazyComponent<typeof import("../../node_modules/element-plus/es/components/dropdown/index")['ElDropdown']>
  LazyElForm: LazyComponent<typeof import("../../node_modules/element-plus/es/components/form/index")['ElForm']>
  LazyElEmpty: LazyComponent<typeof import("../../node_modules/element-plus/es/components/empty/index")['ElEmpty']>
  LazyElDropdownMenu: LazyComponent<typeof import("../../node_modules/element-plus/es/components/dropdown/index")['ElDropdownMenu']>
  LazyElImage: LazyComponent<typeof import("../../node_modules/element-plus/es/components/image/index")['ElImage']>
  LazyElFormItem: LazyComponent<typeof import("../../node_modules/element-plus/es/components/form/index")['ElFormItem']>
  LazyElHeader: LazyComponent<typeof import("../../node_modules/element-plus/es/components/container/index")['ElHeader']>
  LazyElInput: LazyComponent<typeof import("../../node_modules/element-plus/es/components/input/index")['ElInput']>
  LazyElIcon: LazyComponent<typeof import("../../node_modules/element-plus/es/components/icon/index")['ElIcon']>
  LazyElImageViewer: LazyComponent<typeof import("../../node_modules/element-plus/es/components/image-viewer/index")['ElImageViewer']>
  LazyElInputNumber: LazyComponent<typeof import("../../node_modules/element-plus/es/components/input-number/index")['ElInputNumber']>
  LazyElLink: LazyComponent<typeof import("../../node_modules/element-plus/es/components/link/index")['ElLink']>
  LazyElMain: LazyComponent<typeof import("../../node_modules/element-plus/es/components/container/index")['ElMain']>
  LazyElInputTag: LazyComponent<typeof import("../../node_modules/element-plus/es/components/input-tag/index")['ElInputTag']>
  LazyElInputOtp: LazyComponent<typeof import("../../node_modules/element-plus/es/components/input-otp/index")['ElInputOtp']>
  LazyElMenu: LazyComponent<typeof import("../../node_modules/element-plus/es/components/menu/index")['ElMenu']>
  LazyElMention: LazyComponent<typeof import("../../node_modules/element-plus/es/components/mention/index")['ElMention']>
  LazyElMenuItem: LazyComponent<typeof import("../../node_modules/element-plus/es/components/menu/index")['ElMenuItem']>
  LazyElMenuItemGroup: LazyComponent<typeof import("../../node_modules/element-plus/es/components/menu/index")['ElMenuItemGroup']>
  LazyElOptionGroup: LazyComponent<typeof import("../../node_modules/element-plus/es/components/select/index")['ElOptionGroup']>
  LazyElOption: LazyComponent<typeof import("../../node_modules/element-plus/es/components/select/index")['ElOption']>
  LazyElOverlay: LazyComponent<typeof import("../../node_modules/element-plus/es/components/overlay/index")['ElOverlay']>
  LazyElPageHeader: LazyComponent<typeof import("../../node_modules/element-plus/es/components/page-header/index")['ElPageHeader']>
  LazyElPagination: LazyComponent<typeof import("../../node_modules/element-plus/es/components/pagination/index")['ElPagination']>
  LazyElPopconfirm: LazyComponent<typeof import("../../node_modules/element-plus/es/components/popconfirm/index")['ElPopconfirm']>
  LazyElPopper: LazyComponent<typeof import("../../node_modules/element-plus/es/components/popper/index")['ElPopper']>
  LazyElPopover: LazyComponent<typeof import("../../node_modules/element-plus/es/components/popover/index")['ElPopover']>
  LazyElPopperContent: LazyComponent<typeof import("../../node_modules/element-plus/es/components/popper/index")['ElPopperContent']>
  LazyElPopperArrow: LazyComponent<typeof import("../../node_modules/element-plus/es/components/popper/index")['ElPopperArrow']>
  LazyElProgress: LazyComponent<typeof import("../../node_modules/element-plus/es/components/progress/index")['ElProgress']>
  LazyElRadio: LazyComponent<typeof import("../../node_modules/element-plus/es/components/radio/index")['ElRadio']>
  LazyElPopperTrigger: LazyComponent<typeof import("../../node_modules/element-plus/es/components/popper/index")['ElPopperTrigger']>
  LazyElRadioButton: LazyComponent<typeof import("../../node_modules/element-plus/es/components/radio/index")['ElRadioButton']>
  LazyElRadioGroup: LazyComponent<typeof import("../../node_modules/element-plus/es/components/radio/index")['ElRadioGroup']>
  LazyElRow: LazyComponent<typeof import("../../node_modules/element-plus/es/components/row/index")['ElRow']>
  LazyElRate: LazyComponent<typeof import("../../node_modules/element-plus/es/components/rate/index")['ElRate']>
  LazyElResult: LazyComponent<typeof import("../../node_modules/element-plus/es/components/result/index")['ElResult']>
  LazyElScrollbar: LazyComponent<typeof import("../../node_modules/element-plus/es/components/scrollbar/index")['ElScrollbar']>
  LazyElSelect: LazyComponent<typeof import("../../node_modules/element-plus/es/components/select/index")['ElSelect']>
  LazyElSelectV2: LazyComponent<typeof import("../../node_modules/element-plus/es/components/select-v2/index")['ElSelectV2']>
  LazyElSkeletonItem: LazyComponent<typeof import("../../node_modules/element-plus/es/components/skeleton/index")['ElSkeletonItem']>
  LazyElSplitterPanel: LazyComponent<typeof import("../../node_modules/element-plus/es/components/splitter/index")['ElSplitterPanel']>
  LazyElSegmented: LazyComponent<typeof import("../../node_modules/element-plus/es/components/segmented/index")['ElSegmented']>
  LazyElSkeleton: LazyComponent<typeof import("../../node_modules/element-plus/es/components/skeleton/index")['ElSkeleton']>
  LazyElSlider: LazyComponent<typeof import("../../node_modules/element-plus/es/components/slider/index")['ElSlider']>
  LazyElSplitter: LazyComponent<typeof import("../../node_modules/element-plus/es/components/splitter/index")['ElSplitter']>
  LazyElSpace: LazyComponent<typeof import("../../node_modules/element-plus/es/components/space/index")['ElSpace']>
  LazyElStatistic: LazyComponent<typeof import("../../node_modules/element-plus/es/components/statistic/index")['ElStatistic']>
  LazyElStep: LazyComponent<typeof import("../../node_modules/element-plus/es/components/steps/index")['ElStep']>
  LazyElTabPane: LazyComponent<typeof import("../../node_modules/element-plus/es/components/tabs/index")['ElTabPane']>
  LazyElSteps: LazyComponent<typeof import("../../node_modules/element-plus/es/components/steps/index")['ElSteps']>
  LazyElSubMenu: LazyComponent<typeof import("../../node_modules/element-plus/es/components/menu/index")['ElSubMenu']>
  LazyElTable: LazyComponent<typeof import("../../node_modules/element-plus/es/components/table/index")['ElTable']>
  LazyElSwitch: LazyComponent<typeof import("../../node_modules/element-plus/es/components/switch/index")['ElSwitch']>
  LazyElTabs: LazyComponent<typeof import("../../node_modules/element-plus/es/components/tabs/index")['ElTabs']>
  LazyElTableColumn: LazyComponent<typeof import("../../node_modules/element-plus/es/components/table/index")['ElTableColumn']>
  LazyElTableV2: LazyComponent<typeof import("../../node_modules/element-plus/es/components/table-v2/index")['ElTableV2']>
  LazyElTag: LazyComponent<typeof import("../../node_modules/element-plus/es/components/tag/index")['ElTag']>
  LazyElText: LazyComponent<typeof import("../../node_modules/element-plus/es/components/text/index")['ElText']>
  LazyElTimePicker: LazyComponent<typeof import("../../node_modules/element-plus/es/components/time-picker/index")['ElTimePicker']>
  LazyElTimeSelect: LazyComponent<typeof import("../../node_modules/element-plus/es/components/time-select/index")['ElTimeSelect']>
  LazyElTimeline: LazyComponent<typeof import("../../node_modules/element-plus/es/components/timeline/index")['ElTimeline']>
  LazyElTour: LazyComponent<typeof import("../../node_modules/element-plus/es/components/tour/index")['ElTour']>
  LazyElTimelineItem: LazyComponent<typeof import("../../node_modules/element-plus/es/components/timeline/index")['ElTimelineItem']>
  LazyElTooltip: LazyComponent<typeof import("../../node_modules/element-plus/es/components/tooltip/index")['ElTooltip']>
  LazyElIconAddLocation: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['AddLocation']>
  LazyElTourStep: LazyComponent<typeof import("../../node_modules/element-plus/es/components/tour/index")['ElTourStep']>
  LazyElTransfer: LazyComponent<typeof import("../../node_modules/element-plus/es/components/transfer/index")['ElTransfer']>
  LazyElIconAim: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Aim']>
  LazyElIconAlarmClock: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['AlarmClock']>
  LazyElIconApple: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Apple']>
  LazyElIconArrowLeftBold: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowLeftBold']>
  LazyElTree: LazyComponent<typeof import("../../node_modules/element-plus/es/components/tree/index")['ElTree']>
  LazyElTreeSelect: LazyComponent<typeof import("../../node_modules/element-plus/es/components/tree-select/index")['ElTreeSelect']>
  LazyElIconArrowDownBold: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowDownBold']>
  LazyElUpload: LazyComponent<typeof import("../../node_modules/element-plus/es/components/upload/index")['ElUpload']>
  LazyElTreeV2: LazyComponent<typeof import("../../node_modules/element-plus/es/components/tree-v2/index")['ElTreeV2']>
  LazyElIconArrowLeft: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowLeft']>
  LazyElWatermark: LazyComponent<typeof import("../../node_modules/element-plus/es/components/watermark/index")['ElWatermark']>
  LazyElIconArrowRightBold: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowRightBold']>
  LazyElIconArrowDown: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowDown']>
  LazyElIconAvatar: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Avatar']>
  LazyElIconArrowUpBold: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowUpBold']>
  LazyElIconArrowUp: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowUp']>
  LazyElIconArrowRight: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowRight']>
  LazyElIconBell: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Bell']>
  LazyElIconBack: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Back']>
  LazyElIconBellFilled: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['BellFilled']>
  LazyElIconBasketball: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Basketball']>
  LazyElIconBaseball: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Baseball']>
  LazyElIconBottomLeft: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['BottomLeft']>
  LazyElIconBottom: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Bottom']>
  LazyElIconBox: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Box']>
  LazyElIconBicycle: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Bicycle']>
  LazyElIconBottomRight: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['BottomRight']>
  LazyElIconBrushFilled: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['BrushFilled']>
  LazyElIconBrush: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Brush']>
  LazyElIconCamera: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Camera']>
  LazyElIconBriefcase: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Briefcase']>
  LazyElIconBurger: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Burger']>
  LazyElIconBowl: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Bowl']>
  LazyElIconCameraFilled: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CameraFilled']>
  LazyElIconCalendar: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Calendar']>
  LazyElIconCaretBottom: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CaretBottom']>
  LazyElIconCaretLeft: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CaretLeft']>
  LazyElIconChatLineSquare: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ChatLineSquare']>
  LazyElIconCaretRight: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CaretRight']>
  LazyElIconCellphone: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Cellphone']>
  LazyElIconChatDotSquare: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ChatDotSquare']>
  LazyElIconChatLineRound: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ChatLineRound']>
  LazyElIconCaretTop: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CaretTop']>
  LazyElIconChatRound: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ChatRound']>
  LazyElIconChatDotRound: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ChatDotRound']>
  LazyElIconChecked: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Checked']>
  LazyElIconCherry: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Cherry']>
  LazyElIconCheck: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Check']>
  LazyElIconChatSquare: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ChatSquare']>
  LazyElIconChromeFilled: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ChromeFilled']>
  LazyElIconCircleCloseFilled: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CircleCloseFilled']>
  LazyElIconChicken: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Chicken']>
  LazyElIconCirclePlus: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CirclePlus']>
  LazyElIconCircleClose: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CircleClose']>
  LazyElIconCircleCheckFilled: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CircleCheckFilled']>
  LazyElIconClock: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Clock']>
  LazyElIconClose: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Close']>
  LazyElIconCircleCheck: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CircleCheck']>
  LazyElIconCoin: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Coin']>
  LazyElIconCirclePlusFilled: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CirclePlusFilled']>
  LazyElIconCloudy: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Cloudy']>
  LazyElIconCloseBold: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CloseBold']>
  LazyElIconCoffee: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Coffee']>
  LazyElIconColdDrink: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ColdDrink']>
  LazyElIconCoffeeCup: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CoffeeCup']>
  LazyElIconCoordinate: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Coordinate']>
  LazyElIconCollection: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Collection']>
  LazyElIconCompass: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Compass']>
  LazyElIconCollectionTag: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CollectionTag']>
  LazyElIconConnection: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Connection']>
  LazyElIconComment: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Comment']>
  LazyElIconCreditCard: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CreditCard']>
  LazyElIconCrop: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Crop']>
  LazyElIconCpu: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Cpu']>
  LazyElIconDArrowLeft: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DArrowLeft']>
  LazyElIconCopyDocument: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CopyDocument']>
  LazyElIconDataLine: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DataLine']>
  LazyElIconDArrowRight: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DArrowRight']>
  LazyElIconDCaret: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DCaret']>
  LazyElIconDelete: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Delete']>
  LazyElIconDeleteFilled: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DeleteFilled']>
  LazyElIconDataAnalysis: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DataAnalysis']>
  LazyElIconDataBoard: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DataBoard']>
  LazyElIconDessert: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Dessert']>
  LazyElIconDishDot: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DishDot']>
  LazyElIconDiscount: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Discount']>
  LazyElIconDeleteLocation: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DeleteLocation']>
  LazyElIconDish: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Dish']>
  LazyElIconDocumentCopy: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DocumentCopy']>
  LazyElIconDocumentAdd: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DocumentAdd']>
  LazyElIconDocument: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Document']>
  LazyElIconDocumentDelete: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DocumentDelete']>
  LazyElIconDocumentChecked: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DocumentChecked']>
  LazyElIconEdit: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Edit']>
  LazyElIconDocumentRemove: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DocumentRemove']>
  LazyElIconEditPen: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['EditPen']>
  LazyElIconEleme: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Eleme']>
  LazyElIconElemeFilled: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ElemeFilled']>
  LazyElIconDownload: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Download']>
  LazyElIconFailed: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Failed']>
  LazyElIconExpand: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Expand']>
  LazyElIconElementPlus: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ElementPlus']>
  LazyElIconFemale: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Female']>
  LazyElIconFilm: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Film']>
  LazyElIconDrizzling: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Drizzling']>
  LazyElIconFinished: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Finished']>
  LazyElIconFirstAidKit: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['FirstAidKit']>
  LazyElIconFlag: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Flag']>
  LazyElIconFilter: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Filter']>
  LazyElIconFiles: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Files']>
  LazyElIconFold: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Fold']>
  LazyElIconFolderChecked: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['FolderChecked']>
  LazyElIconFolder: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Folder']>
  LazyElIconFolderAdd: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['FolderAdd']>
  LazyElIconFolderRemove: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['FolderRemove']>
  LazyElIconFood: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Food']>
  LazyElIconFolderDelete: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['FolderDelete']>
  LazyElIconFolderOpened: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['FolderOpened']>
  LazyElIconFries: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Fries']>
  LazyElIconGoblet: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Goblet']>
  LazyElIconForkSpoon: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ForkSpoon']>
  LazyElIconGobletFull: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['GobletFull']>
  LazyElIconFootball: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Football']>
  LazyElIconGobletSquare: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['GobletSquare']>
  LazyElIconGoldMedal: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['GoldMedal']>
  LazyElIconFullScreen: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['FullScreen']>
  LazyElIconGobletSquareFull: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['GobletSquareFull']>
  LazyElIconGoodsFilled: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['GoodsFilled']>
  LazyElIconGoods: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Goods']>
  LazyElIconGrid: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Grid']>
  LazyElIconHeadset: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Headset']>
  LazyElIconHandbag: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Handbag']>
  LazyElIconGuide: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Guide']>
  LazyElIconHelp: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Help']>
  LazyElIconHelpFilled: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['HelpFilled']>
  LazyElIconHide: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Hide']>
  LazyElIconHomeFilled: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['HomeFilled']>
  LazyElIconHistogram: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Histogram']>
  LazyElIconGrape: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Grape']>
  LazyElIconHouse: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['House']>
  LazyElIconIceCreamSquare: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['IceCreamSquare']>
  LazyElIconIceDrink: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['IceDrink']>
  LazyElIconIceCreamRound: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['IceCreamRound']>
  LazyElIconHotWater: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['HotWater']>
  LazyElIconIceCream: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['IceCream']>
  LazyElIconInfoFilled: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['InfoFilled']>
  LazyElIconIphone: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Iphone']>
  LazyElIconKey: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Key']>
  LazyElIconLightning: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Lightning']>
  LazyElIconKnifeFork: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['KnifeFork']>
  LazyElIconIceTea: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['IceTea']>
  LazyElIconLocation: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Location']>
  LazyElIconLink: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Link']>
  LazyElIconList: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['List']>
  LazyElIconLocationFilled: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['LocationFilled']>
  LazyElIconLoading: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Loading']>
  LazyElIconLocationInformation: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['LocationInformation']>
  LazyElIconLock: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Lock']>
  LazyElIconMagnet: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Magnet']>
  LazyElIconMagicStick: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MagicStick']>
  LazyElIconLollipop: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Lollipop']>
  LazyElIconMenu: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Menu']>
  LazyElIconMedal: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Medal']>
  LazyElIconManagement: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Management']>
  LazyElIconMapLocation: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MapLocation']>
  LazyElIconMale: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Male']>
  LazyElIconMemo: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Memo']>
  LazyElIconMessage: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Message']>
  LazyElIconMicrophone: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Microphone']>
  LazyElIconMoney: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Money']>
  LazyElIconMic: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Mic']>
  LazyElIconMinus: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Minus']>
  LazyElIconMoon: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Moon']>
  LazyElIconMilkTea: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MilkTea']>
  LazyElIconMoonNight: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MoonNight']>
  LazyElIconMonitor: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Monitor']>
  LazyElIconMessageBox: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MessageBox']>
  LazyElIconMostlyCloudy: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MostlyCloudy']>
  LazyElIconMore: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['More']>
  LazyElIconMoreFilled: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MoreFilled']>
  LazyElIconNoSmoking: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['NoSmoking']>
  LazyElIconMuteNotification: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MuteNotification']>
  LazyElIconMouse: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Mouse']>
  LazyElIconMute: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Mute']>
  LazyElIconMug: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Mug']>
  LazyElIconNotebook: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Notebook']>
  LazyElIconNotification: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Notification']>
  LazyElIconOfficeBuilding: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['OfficeBuilding']>
  LazyElIconOdometer: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Odometer']>
  LazyElIconOpen: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Open']>
  LazyElIconOperation: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Operation']>
  LazyElIconOrange: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Orange']>
  LazyElIconPaperclip: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Paperclip']>
  LazyElIconPicture: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Picture']>
  LazyElIconPartlyCloudy: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['PartlyCloudy']>
  LazyElIconOpportunity: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Opportunity']>
  LazyElIconPhone: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Phone']>
  LazyElIconPear: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Pear']>
  LazyElIconPictureRounded: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['PictureRounded']>
  LazyElIconPictureFilled: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['PictureFilled']>
  LazyElIconPieChart: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['PieChart']>
  LazyElIconPlatform: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Platform']>
  LazyElIconPhoneFilled: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['PhoneFilled']>
  LazyElIconPlus: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Plus']>
  LazyElIconPosition: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Position']>
  LazyElIconPointer: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Pointer']>
  LazyElIconPostcard: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Postcard']>
  LazyElIconPlace: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Place']>
  LazyElIconPresent: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Present']>
  LazyElIconPouring: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Pouring']>
  LazyElIconPriceTag: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['PriceTag']>
  LazyElIconRank: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Rank']>
  LazyElIconReading: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Reading']>
  LazyElIconQuartzWatch: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['QuartzWatch']>
  LazyElIconPrinter: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Printer']>
  LazyElIconPromotion: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Promotion']>
  LazyElIconReadingLamp: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ReadingLamp']>
  LazyElIconRefreshLeft: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['RefreshLeft']>
  LazyElIconQuestionFilled: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['QuestionFilled']>
  LazyElIconRemove: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Remove']>
  LazyElIconRemoveFilled: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['RemoveFilled']>
  LazyElIconRefrigerator: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Refrigerator']>
  LazyElIconRefreshRight: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['RefreshRight']>
  LazyElIconScaleToOriginal: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ScaleToOriginal']>
  LazyElIconSchool: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['School']>
  LazyElIconRefresh: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Refresh']>
  LazyElIconRight: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Right']>
  LazyElIconScissor: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Scissor']>
  LazyElIconSetting: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Setting']>
  LazyElIconSearch: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Search']>
  LazyElIconSelect: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Select']>
  LazyElIconSemiSelect: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SemiSelect']>
  LazyElIconSetUp: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SetUp']>
  LazyElIconSell: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Sell']>
  LazyElIconShare: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Share']>
  LazyElIconService: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Service']>
  LazyElIconShip: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Ship']>
  LazyElIconShoppingBag: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ShoppingBag']>
  LazyElIconShoppingTrolley: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ShoppingTrolley']>
  LazyElIconShoppingCartFull: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ShoppingCartFull']>
  LazyElIconShop: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Shop']>
  LazyElIconSmoking: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Smoking']>
  LazyElIconSoldOut: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SoldOut']>
  LazyElIconSort: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Sort']>
  LazyElIconShoppingCart: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ShoppingCart']>
  LazyElIconSoccer: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Soccer']>
  LazyElIconSortDown: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SortDown']>
  LazyElIconStamp: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Stamp']>
  LazyElIconSortUp: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SortUp']>
  LazyElIconSuccessFilled: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SuccessFilled']>
  LazyElIconStar: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Star']>
  LazyElIconStopwatch: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Stopwatch']>
  LazyElIconStarFilled: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['StarFilled']>
  LazyElIconSuitcaseLine: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SuitcaseLine']>
  LazyElIconSugar: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Sugar']>
  LazyElIconSuitcase: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Suitcase']>
  LazyElIconSwitch: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Switch']>
  LazyElIconSunny: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Sunny']>
  LazyElIconSunrise: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Sunrise']>
  LazyElIconSunset: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Sunset']>
  LazyElIconSwitchButton: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SwitchButton']>
  LazyElIconTakeawayBox: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['TakeawayBox']>
  LazyElIconTicket: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Ticket']>
  LazyElIconSwitchFilled: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SwitchFilled']>
  LazyElIconTools: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Tools']>
  LazyElIconTopRight: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['TopRight']>
  LazyElIconTimer: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Timer']>
  LazyElIconTickets: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Tickets']>
  LazyElIconTop: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Top']>
  LazyElIconToiletPaper: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ToiletPaper']>
  LazyElIconTrendCharts: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['TrendCharts']>
  LazyElIconTrophyBase: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['TrophyBase']>
  LazyElIconTrophy: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Trophy']>
  LazyElIconTopLeft: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['TopLeft']>
  LazyElIconUmbrella: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Umbrella']>
  LazyElIconUpload: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Upload']>
  LazyElIconUnlock: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Unlock']>
  LazyElIconUploadFilled: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['UploadFilled']>
  LazyElIconUserFilled: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['UserFilled']>
  LazyElIconUser: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['User']>
  LazyElIconTurnOff: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['TurnOff']>
  LazyElIconVan: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Van']>
  LazyElIconVideoCameraFilled: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['VideoCameraFilled']>
  LazyElIconVideoPause: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['VideoPause']>
  LazyElIconVideoCamera: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['VideoCamera']>
  LazyElIconVideoPlay: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['VideoPlay']>
  LazyElIconWalletFilled: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['WalletFilled']>
  LazyElIconView: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['View']>
  LazyElIconWallet: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Wallet']>
  LazyElIconWatermelon: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Watermelon']>
  LazyElIconWarning: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Warning']>
  LazyElIconWarnTriangleFilled: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['WarnTriangleFilled']>
  LazyElIconWatch: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Watch']>
  LazyElIconZoomIn: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ZoomIn']>
  LazyElIconZoomOut: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ZoomOut']>
  LazyElIconWindPower: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['WindPower']>
  LazyElIconWarningFilled: LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['WarningFilled']>
  LazyNuxtPage: LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
  LazyNoScript: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  LazyLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
  LazyBase: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
  LazyTitle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
  LazyMeta: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
  LazyStyle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
  LazyHead: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
  LazyHtml: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
  LazyBody: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
  LazyNuxtIsland: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
